# Change these first
owner: xkrrudah # Your GitHub organization or username, where this repository lives
repo: status-website # The name of this repository

sites:
  - name: cms
    url: https://cms.thisistak.me
  - name: ems
    url: https://ems.thisistak.me
  - name: git
    url: https://git.thisistak.me
  - name: mail-server
    url: https://mail.thisistak.me
  - name: blog
    url: https://blog.thisistak.me
  - name: chat
    url: https://chat.thisistak.me
  - name: nas
    url: https://nas.thisistak.me
  - name: router
    url: https://router.thisistak.me
    ipv4: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.thisistak.me
  # baseUrl: /
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: thisistak Infra Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
